version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
test: off
artifacts:
- path: build/nuget/*.nupkg
  name: nuget
build_script:
- ps: ./build.ps1 Build
test_script:
- ps: ./build.ps1 RunTests
- ps: ./build.ps1 CreateNuget
deploy:
  provider: NuGet
  server: https://www.myget.org/F/akkadotnet-contrib/api/v2/package
  api_key:
    secure: yoMgcchmDuXbvT90bgrUTOUNYgAId6QI0nofIOtnlfWzMjDEWfOqNqqTGPY+02M+
  skip_symbols: false
  symbol_server: https://www.myget.org/F/akkadotnet-contrib/symbols/api/v2/package
  artifact: /.*\.nupkg/
